#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "main.h"

// --- MANUAL JSON PARSER (No Deps) ---
// Finds "key": "value" and extracts value
void parse_json_value(const char* json, const char* key, char* dest, int max_len) {
    char search[128];
    sprintf(search, "\"%s\"", key); // Look for "key"
    
    char* found = strstr(json, search);
    if (!found) {
        // Default if missing
        strcpy(dest, "MISSING");
        return;
    }

    // Move past key
    char* start = strchr(found, ':');
    if (!start) return;
    
    // Find opening quote
    start = strchr(start, '"');
    if (!start) return;
    start++; // Skip quote

    // Copy until closing quote
    int i = 0;
    while (start[i] != '"' && start[i] != '\0' && i < max_len - 1) {
        dest[i] = start[i];
        i++;
    }
    dest[i] = '\0';
}

int load_config(const char* filename, SiteConfig* config) {
    FILE* f = fopen(filename, "r");
    if (!f) {
        printf("❌ Error: Could not open %s\n", filename);
        return 0;
    }

    // Read entire file into buffer (Limit 4KB for simplicity)
    char buffer[4096];
    size_t len = fread(buffer, 1, 4096, f);
    buffer[len] = '\0';
    fclose(f);

    printf("   -> Parsing JSON...\n");
    parse_json_value(buffer, "title", config->title, 128);
    parse_json_value(buffer, "tagline", config->tagline, 256);
    parse_json_value(buffer, "hero_text", config->hero_text, 512);
    parse_json_value(buffer, "cta_text", config->cta_text, 128);
    parse_json_value(buffer, "cta_link", config->cta_link, 128);
    parse_json_value(buffer, "bg_color", config->bg_color, 32);
    parse_json_value(buffer, "accent_color", config->accent_color, 32);
    
    // Default text color if not found (simple logic)
    strcpy(config->text_color, "#ffffff");

    return 1;
}

int generate_html(const SiteConfig* config) {
    char path[256];
    sprintf(path, "apps/sitegen/output/index.html"); // Path relative to repo root execution usually, but we run from binary
    // Fix: We assume running from monorepo root or finding relative path. 
    // Ideally pass output dir arg. For MVP, we hardcode relative to CWD or specific path.
    // Let's write to "output/index.html" assuming we cd there or use absolute in script.
    
    FILE* f = fopen("output/index.html", "w");
    if (!f) return 0;

    fprintf(f, "<!DOCTYPE html>\n<html>\n<head>\n");
    fprintf(f, "  <meta charset=\"UTF-8\">\n");
    fprintf(f, "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
    fprintf(f, "  <title>%s</title>\n", config->title);
    fprintf(f, "  <link rel=\"stylesheet\" href=\"style.css\">\n");
    fprintf(f, "</head>\n<body>\n");
    
    fprintf(f, "  <div class=\"container\">\n");
    fprintf(f, "    <header>\n");
    fprintf(f, "      <div class=\"logo\">%s</div>\n", config->title);
    fprintf(f, "    </header>\n");
    
    fprintf(f, "    <main class=\"hero\">\n");
    fprintf(f, "      <h1>%s</h1>\n", config->tagline);
    fprintf(f, "      <p class=\"subtext\">%s</p>\n", config->hero_text);
    fprintf(f, "      <a href=\"%s\" class=\"cta-button\">%s</a>\n", config->cta_link, config->cta_text);
    fprintf(f, "    </main>\n");
    
    fprintf(f, "    <footer>\n");
    fprintf(f, "      <p>Generated by CSSG (C Static Site Generator) v1.0</p>\n");
    fprintf(f, "    </footer>\n");
    fprintf(f, "  </div>\n");
    
    fprintf(f, "</body>\n</html>\n");
    fclose(f);
    return 1;
}

int generate_css(const SiteConfig* config) {
    FILE* f = fopen("output/style.css", "w");
    if (!f) return 0;

    fprintf(f, "body {\n");
    fprintf(f, "  margin: 0; padding: 0;\n");
    fprintf(f, "  background-color: %s;\n", config->bg_color);
    fprintf(f, "  color: %s;\n", config->text_color);
    fprintf(f, "  font-family: 'Courier New', Courier, monospace;\n");
    fprintf(f, "  text-align: center;\n");
    fprintf(f, "}\n");

    fprintf(f, ".container { max-width: 800px; margin: 0 auto; padding: 2rem; }\n");
    
    fprintf(f, "header { margin-bottom: 4rem; text-align: left; }\n");
    fprintf(f, ".logo { font-weight: bold; font-size: 1.2rem; letter-spacing: 2px; }\n");

    fprintf(f, ".hero { margin-top: 10vh; }\n");
    fprintf(f, "h1 { font-size: 3rem; margin-bottom: 1rem; line-height: 1.1; }\n");
    fprintf(f, ".subtext { font-size: 1.2rem; opacity: 0.8; margin-bottom: 3rem; max-width: 600px; margin-left: auto; margin-right: auto; }\n");

    fprintf(f, ".cta-button {\n");
    fprintf(f, "  display: inline-block;\n");
    fprintf(f, "  background-color: transparent;\n");
    fprintf(f, "  color: %s;\n", config->accent_color);
    fprintf(f, "  border: 2px solid %s;\n", config->accent_color);
    fprintf(f, "  padding: 15px 30px;\n");
    fprintf(f, "  font-size: 1.1rem;\n");
    fprintf(f, "  text-decoration: none;\n");
    fprintf(f, "  text-transform: uppercase;\n");
    fprintf(f, "  font-weight: bold;\n");
    fprintf(f, "  transition: all 0.2s;\n");
    fprintf(f, "}\n");

    fprintf(f, ".cta-button:hover {\n");
    fprintf(f, "  background-color: %s;\n", config->accent_color);
    fprintf(f, "  color: %s;\n", config->bg_color);
    fprintf(f, "  box-shadow: 0 0 15px %s;\n", config->accent_color);
    fprintf(f, "}\n");

    fprintf(f, "footer { margin-top: 5rem; font-size: 0.8rem; opacity: 0.4; }\n");

    fclose(f);
    return 1;
}

int main(int argc, char* argv[]) {
    printf("⚡ CSSG v1.0 Starting...\n");
    
    const char* file = "content.json";
    if (argc > 1) file = argv[1];

    SiteConfig config;
    if (!load_config(file, &config)) return 1;
    printf("   ✅ Config Loaded: %s\n", config.title);

    if (generate_html(&config)) printf("   ✅ Generated HTML\n");
    else printf("   ❌ Failed HTML\n");

    if (generate_css(&config)) printf("   ✅ Generated CSS\n");
    else printf("   ❌ Failed CSS\n");

    printf("✨ Done. Uploading artifacts...\n");
    return 0;
}
